[package]
name = "tryzub-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
libc = "0.2"
once_cell = "1.18"
crossbeam-channel = "0.5"
parking_lot = "0.12"
dashmap = "5.5"
