[package]
name = "tryzub-runtime"
version = "1.0.0"
edition = "2021"
authors = ["Мартинюк Євген <evgenmart@gmail.com>"]

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
libc = "0.2"
once_cell = "1.18"
crossbeam-channel = "0.5"
parking_lot = "0.12"
dashmap = "5.5"
num_cpus = "1.16"
